image: node:18

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/
    - .npm/

build:
  stage: build
  tags:
    - biscord-frontend-runner
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour
  only:
    - main

deploy:
  stage: deploy
  tags:
    - biscord-frontend-runner
  script:
    - echo $AWS_ACCESS_KEY_ID
    - echo $AWS_SECRET_ACCESS_KEY
    - echo $SERVERLESS_ACCESS_KEY
    - echo ${SERVERLESS_ACCESS_KEY}
    - npm install -g serverless
    - serverless deploy
    - serverless client deploy --no-confirm

  dependencies:
    - build
  only:
    - main
