export const MODAL = {
  CREATE_SERVER: 'CREATE_SERVER',
  EDIT_SERVER: 'EDIT_SERVER',
  DELETE_SERVER: 'DELETE_SERVER',
  CREATE_CHANNEL: 'CREATE_CHANNEL',
  DELETE_CHANNEL: 'DELETE_CHANNEL',
  INVIDE_MEMBER: 'INVIDE_MEMBER',
  USER_PROFILE: 'USER_PROFILE',
  USER_WITHDRAW: 'USER_WITHDRAW',
  JOIN_SERVER: 'JOIN_SERVER',
  CALL_NOTIFICATION: 'CALL_NOTIFICATION',
  NONE: 'NONE',
} as const;
