export const ModalType = {
  CREATE_SERVER: 'CREATE_SERVER',
  EDIT_SERVER: 'EDIT_SERVER',
  DELETE_SERVER: 'DELETE_SERVER',
  CREATE_CHANNEL: 'CREATE_CHANNEL',
  DELETE_CHANNEL: 'DELETE_CHANNEL',
  INVIDE_MEMBER: 'INVIDE_MEMBER',
  USER_PROFILE: 'USER_PROFILE',
  USER_SIGNOFF: 'USER_SIGNOFF',
  NONE: 'NONE',
} as const;
