name: mirror main repository to gitlab

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get last commit author email
        id: get-author-email
        run: echo "email=$(git log -1 --pretty=format:'%ae')" >> $GITHUB_OUTPUT

      - name: Set GitLab credentials
        id: set-credentials
        run: |
          if [ "${{ steps.get-author-email.outputs.email }}" = "limjunhee4575@gmail.com" ]; then
            echo "password=${{ secrets.GITLAB_PASSWORD_LIMJUNHEE }}" >> $GITHUB_OUTPUT
            echo "username=limjunhee" >> $GITHUB_OUTPUT
          else
            echo "password=${{ secrets.GITLAB_PASSWORD }}" >> $GITHUB_OUTPUT
            echo "username=limjunhee" >> $GITHUB_OUTPUT
          fi

      - name: Mirror to GitLab
        uses: yesolutions/mirror-action@master
        with:
          REMOTE: "https://kdt-gitlab.elice.io/pttrack/class_01/web_project_i/team06/biscord_fe.git"
          GIT_USERNAME: ${{ steps.set-credentials.outputs.username }}
          GIT_PASSWORD: ${{ steps.set-credentials.outputs.password }}
